---

- block:
    - when: audiobookshelf_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - when: audiobookshelf_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"
  tags:
    - setup-all
    - setup-audiobookshelf
    - install-all
    - install-audiobookshelf

- block:
    - when: not audiobookshelf_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
  tags:
    - setup-all
    - setup-audiobookshelf
